"""dish costing fields

Revision ID: 2222ef8de48b
Revises: 4a01987d5371
Create Date: 2026-09-21 13:39:32.285636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2222ef8de48b'
down_revision: Union[str, Sequence[str], None] = '4a01987d5371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('menu_items', sa.Column('packaging_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'packaging_cost')
    op.drop_column('inventory_items', 'unit_cost')
    # ### end Alembic commands ###
