"""distance based delivery

Revision ID: a1875b380fd0
Revises: a7596c26f7b0
Create Date: 2026-09-22 12:49:57.599946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1875b380fd0'
down_revision: Union[str, Sequence[str], None] = 'a7596c26f7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_distance_km', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('settings', sa.Column('delivery_per_km', sa.Numeric(precision=10, scale=2), nullable=False, server_default='26'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'delivery_per_km')
    op.drop_column('orders', 'delivery_distance_km')
    # ### end Alembic commands ###
