"""expand settings

Revision ID: a7596c26f7b0
Revises: c85de0925c5d
Create Date: 2026-09-21 19:05:55.853577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7596c26f7b0'
down_revision: Union[str, Sequence[str], None] = 'c85de0925c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('restaurant_name', sa.String(length=150), nullable=False, server_default="Mehak's Kitchen"))
    op.add_column('settings', sa.Column('contact_phone', sa.String(length=30), nullable=True))
    op.add_column('settings', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('opening_hours', sa.String(length=120), nullable=True))
    op.add_column('settings', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='80'))
    op.add_column('settings', sa.Column('delivery_radius_km', sa.Numeric(precision=5, scale=1), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'delivery_radius_km')
    op.drop_column('settings', 'delivery_fee')
    op.drop_column('settings', 'opening_hours')
    op.drop_column('settings', 'address')
    op.drop_column('settings', 'contact_phone')
    op.drop_column('settings', 'restaurant_name')
    # ### end Alembic commands ###
